'use client';

import { useCallback, useEffect, useState, useTransition } from 'react';
import { createClient } from '@/lib/supabase/client';

// Authenticator-app (TOTP) enrolment + management for the signed-in user (#176).
// Rendered on the admin-only /staff/security page. Uses Supabase native MFA, so
// the shared secret is generated by Supabase and never stored in our tables.
type Msg = { kind: 'ok' | 'err' | 'info'; text: string } | null;

export default function MfaEnrollment() {
  const supabase = createClient();
  const [loading, setLoading] = useState(true);
  const [hasVerified, setHasVerified] = useState(false);
  const [enroll, setEnroll] = useState<{ factorId: string; qr: string; secret: string } | null>(null);
  const [code, setCode] = useState('');
  const [msg, setMsg] = useState<Msg>(null);
  const [busy, start] = useTransition();

  const refresh = useCallback(async () => {
    const { data, error } = await supabase.auth.mfa.listFactors();
    if (error) {
      setMsg({ kind: 'err', text: 'Could not read your security factors. If MFA has just been enabled, reload the page.' });
    } else {
      setHasVerified(!!data?.totp?.some((f) => f.status === 'verified'));
    }
    setLoading(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  function startEnroll() {
    setMsg(null);
    start(async () => {
      // Clear any half-finished (unverified) TOTP factors so a fresh enrolment
      // never collides with a stale one.
      const { data: list } = await supabase.auth.mfa.listFactors();
      for (const f of list?.totp ?? []) {
        if (f.status !== 'verified') await supabase.auth.mfa.unenroll({ factorId: f.id });
      }
      const { data, error } = await supabase.auth.mfa.enroll({ factorType: 'totp' });
      if (error || !data) {
        setMsg({
          kind: 'err',
          text: 'Could not start enrolment. An administrator may need to enable TOTP MFA for this project in Supabase first.',
        });
        return;
      }
      setEnroll({ factorId: data.id, qr: data.totp.qr_code, secret: data.totp.secret });
      setCode('');
    });
  }

  function confirmEnroll() {
    if (!enroll) return;
    setMsg(null);
    const clean = code.replace(/\D/g, '').slice(0, 6);
    if (clean.length < 6) {
      setMsg({ kind: 'err', text: 'Enter the 6-digit code shown in your authenticator app.' });
      return;
    }
    start(async () => {
      const { data: ch, error: cErr } = await supabase.auth.mfa.challenge({ factorId: enroll.factorId });
      if (cErr || !ch) {
        setMsg({ kind: 'err', text: 'Could not verify just now. Please try again.' });
        return;
      }
      const { error: vErr } = await supabase.auth.mfa.verify({ factorId: enroll.factorId, challengeId: ch.id, code: clean });
      if (vErr) {
        setMsg({ kind: 'err', text: 'That code was not correct. Enter the current code from your app and try again.' });
        return;
      }
      setEnroll(null);
      setCode('');
      setMsg({ kind: 'ok', text: 'Authenticator app added. You will be asked for a code at sign-in from now on.' });
      await refresh();
    });
  }

  function cancelEnroll() {
    const pending = enroll;
    setEnroll(null);
    setCode('');
    setMsg(null);
    if (pending) {
      start(async () => {
        await supabase.auth.mfa.unenroll({ factorId: pending.factorId });
      });
    }
  }

  function removeFactor() {
    if (!confirm('Remove the authenticator app from your account? You will no longer be asked for an app code at sign-in.')) return;
    setMsg(null);
    start(async () => {
      const { data } = await supabase.auth.mfa.listFactors();
      for (const f of data?.totp ?? []) {
        await supabase.auth.mfa.unenroll({ factorId: f.id });
      }
      setMsg({ kind: 'info', text: 'Authenticator app removed.' });
      await refresh();
    });
  }

  const banner = msg ? (
    <div
      style={{
        margin: '10px 0 0',
        borderRadius: 12,
        fontSize: 12.5,
        fontWeight: 600,
        padding: '10px 13px',
        border: `1px solid ${msg.kind === 'ok' ? 'rgba(166,205,53,0.4)' : msg.kind === 'err' ? 'rgba(239,90,90,0.4)' : 'var(--border)'}`,
        color: msg.kind === 'ok' ? 'var(--lime2)' : msg.kind === 'err' ? '#ef7f7f' : 'var(--muted)',
        background: msg.kind === 'ok' ? 'rgba(166,205,53,0.08)' : msg.kind === 'err' ? 'rgba(239,90,90,0.08)' : 'var(--surface2)',
      }}
    >
      {msg.text}
    </div>
  ) : null;

  return (
    <div className="card card-pad" style={{ marginBottom: 16 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
        <div style={{ fontWeight: 700, fontSize: 15 }}>
          <i className="fa-solid fa-mobile-screen-button" style={{ marginRight: 8, opacity: 0.7 }} />
          Authenticator app (2FA)
        </div>
        {loading ? (
          <span className="badge" style={{ fontSize: 10.5 }}>Checking...</span>
        ) : hasVerified ? (
          <span className="badge badge-good"><i className="fa-solid fa-circle-check" /> Active</span>
        ) : (
          <span className="badge badge-warn"><i className="fa-solid fa-triangle-exclamation" /> Not set up</span>
        )}
      </div>

      <div className="muted" style={{ fontSize: 12.5, marginTop: 8 }}>
        An extra sign-in step for high-privilege accounts. Scan the QR code with an authenticator app (Google Authenticator, Microsoft Authenticator, 1Password, Authy) and enter the 6-digit code it shows. You will then be asked for a fresh code each time you sign in.
      </div>

      {!loading && !enroll && !hasVerified ? (
        <button className="btn btn-primary btn-sm mt-2" onClick={startEnroll} disabled={busy} style={{ marginTop: 12 }}>
          {busy ? 'Working...' : (<><i className="fa-solid fa-plus" /> Set up authenticator</>)}
        </button>
      ) : null}

      {!loading && !enroll && hasVerified ? (
        <button className="btn btn-ghost btn-sm" onClick={removeFactor} disabled={busy} style={{ marginTop: 12 }}>
          {busy ? 'Working...' : (<><i className="fa-solid fa-trash-can" /> Remove authenticator</>)}
        </button>
      ) : null}

      {enroll ? (
        <div style={{ marginTop: 14, display: 'flex', gap: 18, flexWrap: 'wrap', alignItems: 'flex-start' }}>
          <div style={{ background: '#fff', padding: 10, borderRadius: 12, lineHeight: 0 }}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={enroll.qr} alt="Authenticator QR code" width={168} height={168} style={{ display: 'block' }} />
          </div>
          <div style={{ flex: '1 1 220px', minWidth: 220 }}>
            <div className="muted" style={{ fontSize: 12 }}>
              Cannot scan? Enter this key manually:
            </div>
            <div className="num" style={{ fontSize: 12.5, wordBreak: 'break-all', margin: '4px 0 12px', color: 'var(--text)' }}>
              {enroll.secret}
            </div>
            <div className="field">
              <label>6-digit code from the app</label>
              <input
                className="input"
                value={code}
                onChange={(e) => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
                inputMode="numeric"
                autoComplete="one-time-code"
                placeholder="000000"
                style={{ letterSpacing: 5, fontSize: 18, textAlign: 'center', maxWidth: 200 }}
              />
            </div>
            <div style={{ display: 'flex', gap: 10, marginTop: 10, flexWrap: 'wrap' }}>
              <button className="btn btn-primary btn-sm" onClick={confirmEnroll} disabled={busy}>
                {busy ? 'Verifying...' : (<><i className="fa-solid fa-check" /> Verify &amp; activate</>)}
              </button>
              <button className="btn btn-ghost btn-sm" onClick={cancelEnroll} disabled={busy}>
                Cancel
              </button>
            </div>
          </div>
        </div>
      ) : null}

      {banner}
    </div>
  );
}
